[package]
name = "mpsd"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.4"
aho-corasick = "1.1.3"
bytes = "1.6.1"
colored = "2.1.0"
clap = { version = "4.5.11", features = ["derive"] }
